flaire/closet/urls.py
from django.urls import path

from . import views
from .views import *

app_name = "closet"

urlpatterns = [
    path("images/", views.clothing_item_images, name="get_clothing_images"),
    path("", closet, name="closet"),
    path("add-clothing-item/", views.add_clothing_item, name="add_clothing_item"),
    path("save-outfit/", views.save_outfit, name="save_outfit"),
    path(
        "save-outfit-post-metadata/<int:outfit_id>/",
        views.save_outfit_post_metadata,
        name="save_outfit_post_metadata",
    ),
    path("select-ootd/<int:outfit_id>/", views.select_ootd, name="select_ootd"),
    path("delete-ootd/", views.delete_ootd, name="delete_ootd"),
]

flaire/flaire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from django.contrib.auth import views as auth_views
from user_management.views import LikedOutfitsView



def home(request):
    return render(request, "home.html", {"active_tab": "home"})


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user_management.urls")),
    path("closet/", include("closet.urls", namespace="closet")),
    path("", home, name="home"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("showrooms/", include("showrooms.urls", namespace="showrooms")),
    path("social/", include("social.urls", namespace="social")),
    path('liked-outfits/', LikedOutfitsView.as_view(), name='liked_outfits'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flaire/showrooms/urls.py
from django.urls import path

from flaire import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from .views import *

app_name = "showrooms"

urlpatterns = [
    path("", views.showrooms, name="showrooms"),
    path("owned/", views.list_of_showrooms, name="get_showrooms_owned"),
    path("create/", views.create_showroom, name="create_showrooms"),
    path('<slug:slug>-<int:pk>/', views.showroom_detail, name='showroom_detail'),
    path('<int:pk>/outfits/', views.showroom_outfits, name='showroom_outfits'),
    path('<int:pk>/update/', views.edit_showroom, name='edit_showroom'),
    path('<int:pk>/follow/', views.follow_showroom, name='follow_showroom'),
    path('<int:pk>/unfollow/', views.unfollow_showroom, name='unfollow_showroom'),
    path('<int:pk>/add-outfits/', views.create_showroom_outfit_modal, name='add_outfits'),
    path('<int:pk>/accept/', views.accept_showroom_invite, name='accept_showroominv'),
    path('<int:pk>/decline/', views.decline_showroom_invite, name='decline_showroominv'),
    path('<int:pk>/add-outfit/', views.add_outfit_to_showroom, name='add_outfit_to_sr'),
] 

flaire/user_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import (
    LikedOutfitsView,
    OtherUserProfileView,
    OutfitDetailView,
    OutfitGridImagesView,
    ProfileSetupView,
    ProfileView,
    SubmitCommentView,
    UserCreateView,
    UserFollowView,
    UserLoginView,
    WishlistView,
    add_to_closet,
    toggle_like_outfit,
    toggle_wishlist,
    unlike_outfit,
)

app_name = "user_management"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("signup/", UserCreateView.as_view(), name="signup"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile-setup/", ProfileSetupView.as_view(), name="profile_setup"),
    path("liked-outfits/", LikedOutfitsView.as_view(), name="liked_outfits"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path(
        "profile/<str:username>/",
        OtherUserProfileView.as_view(),
        name="other_user_profile",
    ),
    path(
        "api/followers/<str:username>/",
        UserFollowView().get_followers,
        name="get_followers",
    ),
    path(
        "api/following/<str:username>/",
        UserFollowView().get_following,
        name="get_following",
    ),
    path(
        "api/follow/<str:username>/",
        UserFollowView().toggle_follow,
        name="toggle_follow",
    ),
    path(
        "outfit-grid-images/",
        OutfitGridImagesView.as_view(),
        name="get_outfit_images",
    ),
    path(
        "outfit-grid-images/<str:username>/",
        OutfitGridImagesView.as_view(),
        name="get_outfit_images",
    ),
    path("outfit-details/<int:pk>/", OutfitDetailView.as_view(), name="outfit_details"),
    path(
        "submit-comment/<int:outfit_id>/",
        SubmitCommentView.as_view(),
        name="submit-comment",
    ),
    path("toggle-wishlist/<int:item_id>/", toggle_wishlist, name="toggle_wishlist"),
    path(
        "toggle-like-outfit/<int:outfit_id>/",
        toggle_like_outfit,
        name="toggle_like_outfit",
    ),
    path(
        "remove-from-wishlist/<int:item_id>/",
        views.remove_from_wishlist,
        name="remove_from_wishlist",
    ),
    path("unlike-outfit/<int:outfit_id>/", unlike_outfit, name="unlike_outfit"),
    path("add-to-closet/<int:item_id>/", add_to_closet, name="add_to_closet"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flaire/showrooms/forms.py
from django import forms
from .models import *


class ShowroomCreateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs=
            {'class': 'form-control', 'placeholder': 'like "Boho-chic Outfits'}))
    collaborators = forms.ModelMultipleChoiceField(
        queryset=Profile.objects.none(),
        required=False,
        widget=forms.SelectMultiple(attrs=
            {'class': 'select2'})
    ) 

    class Meta:
        model = Showroom
        fields = ['title', 'cover_image', 'is_public', 'tags', 'collaborators']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ShowroomCreateForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['collaborators'].queryset = Profile.objects.exclude(user=user)
        self.fields['tags'].help_text = ''
        self.fields['tags'].widget.attrs.update({
            'placeholder': 'Add up to 3 tags, separated by commas',
            'style': 'width: 30%;'})

flaire/showrooms/views.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from .forms import *
from .models import *
from social.models import Notification

import json

@login_required(login_url="user_management:login")
def showrooms(request):
    return render(
        request, "showrooms/owned-showrooms.html", {"active_tab": "showrooms"}
    )


@login_required(login_url="user_management:login")
def list_of_showrooms(request):
    users_showrooms = (
        Showroom.objects.filter(
            Q(owner=request.user.profile)
            | Q(
                showroomcollaborator__collaborator=request.user.profile,
                showroomcollaborator__status="ACCEPTED",
            )
        )
        .distinct()
        .order_by("-date_created")
    )

    page = int(request.GET.get("page", 1))

    if page == 1:
        showrooms_to_display = users_showrooms[:3]  # first 3
        has_next = users_showrooms.count() > 3
        has_previous = False
        num_pages = (users_showrooms.count() - 3 + 3) // 4 + 1  # +1 for first page
    else:
        remaining_showrooms = users_showrooms[3:]
        paginator = Paginator(remaining_showrooms, 4)
        current_page = paginator.get_page(page - 1)  # shift pages down by 1
        showrooms_to_display = current_page.object_list
        has_next = current_page.has_next()
        has_previous = current_page.has_previous() or True  # always allow going back to page 1
        num_pages = paginator.num_pages + 1  # add page 1


    showroom_data = [
        {
            "id": showroom.id,
            "title": showroom.title,
            "cover_image": showroom.cover_image.url if showroom.cover_image else "",
            "slug": showroom.slug,
        }
        for showroom in showrooms_to_display
    ]

    return JsonResponse({
        "showrooms": showroom_data,
        "has_next": has_next,
        "has_previous": has_previous,
        "current_page": page,
        "num_pages": num_pages
    })


@login_required(login_url='user_management:login')
def showroom_detail(request, pk, slug=None):
    showroom = Showroom.objects.get(pk=pk)
    outfit_count = showroom.outfits.count()
    follower_count = showroom.followers.count()
    accepted_collaborators = ShowroomCollaborator.objects.filter(
        showroom=showroom,
        status='ACCEPTED'
        ).select_related('collaborator')
    invited_collaborators = ShowroomCollaborator.objects.filter(
        showroom=showroom,
        status='PENDING'
        ).select_related('collaborator')


    is_follower = showroom.followers.filter(id=request.user.profile.id).exists()
    is_collaborator = accepted_collaborators.filter(collaborator=request.user.profile).exists()
    is_invited = invited_collaborators.filter(collaborator=request.user.profile).exists()
    is_owner = showroom.owner==request.user.profile

    if slug != showroom.slug:
        return redirect('showrooms:showroom_detail', pk=pk, slug=showroom.slug)
    
    return render(request, 'showrooms/showroom-detail.html', {
        'showroom': showroom,
        'accepted_collaborators': accepted_collaborators,
        'outfit_count': outfit_count,
        'follower_count': follower_count,
        'show_follow_button': not (is_follower or is_collaborator or is_owner),
        'show_edit_button': is_owner or is_collaborator,
        'if_following': is_follower,
        'if_invited': is_invited
    })


@login_required(login_url="user_management:login")
def showroom_outfits(request, pk):
    showroom = Showroom.objects.get(pk=pk)
    outfits = showroom.outfits.all()
    data = []
    for outfit in outfits:
        data.append(
            {
                "id": outfit.id,
                "image": outfit.image.url if outfit.image else "",
            }
        )
    return JsonResponse({"outfits": data})


@login_required(login_url="user_management:login")
def create_showroom(request):
    user_profile = request.user.profile

    if request.method == "POST":
        form = ShowroomCreateForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            showroom = form.save(commit=False)
            showroom.owner = user_profile
            showroom.save()

            collaborators = form.cleaned_data.get('collaborators', [])
            for collab in collaborators:
                ShowroomCollaborator.objects.create(
                    showroom=showroom,
                    collaborator=collab,
                    invited_by=user_profile,
                    status="PENDING",
                )
                Notification.objects.create(
                    sender=user_profile,
                    recipient=collab,
                    message=f"You've been invited to collaborate on '{showroom.title}'",
                    link=reverse('showrooms:showroom_detail', kwargs={
                        'pk': showroom.id,
                        'slug': showroom.slug
                    }),
                    is_read=False
                )

            tags = request.POST.get("tags", "").split(",")
            showroom.tags.set(tags[:3])

            return redirect('showrooms:showroom_detail', pk=showroom.id, slug=showroom.slug)

    else:
        form = ShowroomCreateForm(user=request.user)

    return render(request, 'showrooms/showroom-create.html', {
        'form': form
    })
        

@login_required(login_url='user_management:login')
def create_showroom_outfit_modal(request, pk):
    showroom = Showroom.objects.get(pk=pk)
    user_profile = request.user.profile
    user_outfits = user_profile.outfits.all()
    showroom_outfits = showroom.outfits.all()
    
    available_outfits = user_outfits.exclude(
        id__in=showroom_outfits.values_list('id', flat=True))

    data = []
    for outfit in available_outfits:
        data.append({
        'id': outfit.id,
        'image': outfit.image.url if outfit.image else '',
    })
    return JsonResponse({'outfits': data})


@login_required(login_url='user_management:login')
def add_outfit_to_showroom(request, pk):
    if request.method == 'POST':
        user_profile = request.user.profile
        showroom = get_object_or_404(Showroom, pk=pk)

        data = json.loads(request.body)
        outfit_id = data.get('outfit_id')

        try:
            outfit = Outfit.objects.get(pk=outfit_id, owner=user_profile)
            if not showroom.outfits.filter(pk=outfit.pk).exists():
                ShowroomOutfit.objects.create(showroom=showroom, outfit=outfit)
                return JsonResponse({'success': True})
        except Outfit.DoesNotExist:
            pass

        return JsonResponse({'success': False}, status=400)


@login_required(login_url='user_management:login')
def edit_showroom(request, pk):
    if request.method == "POST":
        try:
            showroom = Showroom.objects.get(pk=pk)
            data = json.loads(request.body)
            new_title = data.get("title", "").strip()

            if new_title:
                showroom.title = new_title
                showroom.save()
                return JsonResponse({"success": True})
            else:
                return JsonResponse({"success": False, "error": "Title is empty"})

        except Exception as e:
            return JsonResponse({"success": False, "error": str(e)})

    return JsonResponse({"success": False, "error": "Invalid request method"})


@login_required(login_url='user_management:login')
def follow_showroom(request, pk):
    if request.method == "POST":
        showroom = Showroom.objects.get(pk=pk)
        user_profile = request.user.profile

        ShowroomFollower.objects.create(showroom=showroom, profile=user_profile)
        Notification.objects.create(
            sender=user_profile,
            recipient=showroom.owner,
            message=f"{user_profile} followed your showroom, '{showroom.title}'",
            link=reverse('showrooms:showroom_detail', kwargs={
                'pk': showroom.id,
                'slug': showroom.slug
            }),
            is_read=False
        )

        return JsonResponse({
            'success': True,
        })
    
def unfollow_showroom(request, pk):
    if request.method == 'POST':
        showroom = Showroom.objects.get(pk=pk)
        user_profile = request.user.profile

        showroom_follow = ShowroomFollower.objects.get(
            showroom=showroom, 
            profile=user_profile)
        showroom_follow.delete()
        
        return JsonResponse({
            'success': True,
        }) 
    

@login_required(login_url='user_management:login')
def accept_showroom_invite(request, pk):
    if request.method == 'POST':
        showroom = Showroom.objects.get(pk=pk)
        user_profile = request.user.profile

        collaborator = ShowroomCollaborator.objects.get(
            showroom=showroom, 
            collaborator=user_profile, 
            status='PENDING')
        
        # thinking of removing this since i think history of invites is still ok !
        # remove_notif = Notification.objects.get(
        #     sender=showroom.owner,
        #     recipient=user_profile,
        #     message=f"You've been invited to collaborate on '{showroom.title}'",
        #     link=reverse('showrooms:showroom_detail', kwargs={'pk': showroom.id, 'slug': showroom.slug}),
        # )
        # remove_notif.delete()
        
        ShowroomFollower.objects.filter(
            showroom=showroom,
            profile=user_profile
        ).delete()
        
        collaborator.status = 'ACCEPTED'
        collaborator.save()
        
        return JsonResponse({
            'success': True,
        })
    
    
@login_required(login_url='user_management:login')
def decline_showroom_invite(request, pk):

flaire/templates/showrooms/outfit-items.html
{% for outfit in outfits %}
  <div class="outfit-thumbnail">
    <img src="{{ outfit.image.url }}" alt="{{ outfit.name }}">
    <p>{{ outfit.name }}</p>
  </div>
{% empty %}
  <p>No outfits found.</p>
{% endfor %}

flaire/templates/showrooms/owned-showrooms.html
{% extends "base.html" %}
{% load static %}
{% block title %}Showrooms{% endblock %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/showrooms/owned-showrooms.css' %}">
{% endblock %}

{% block content %}
<div id="showroom-grid" class="grid-container">
  <div class="thumbnail pagination-arrow">
    <button id="prev-btn" class="arrow-button" disabled>&#8592;</button>
  </div>
  
  <div class="thumbnail pagination-arrow">
    <button id="next-btn" class="arrow-button">&#8594;</button>
  </div>
</div>

<div id="create-modal" class="modal fade">
  <div id="dialog" class="modal-dialog modal-dialog-centered" hx-target="this" hx-swap="outerHTML"></div>
</div>

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'js/showrooms/owned-showrooms.js' %}"></script>
{% endblock %}

flaire/templates/showrooms/showroom-create.html
{% extends "base.html" %}
{% load static %}
{% block title %}Create Showroom{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/showrooms/create-showrooms.css' %}">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}

<h2>Create showroom</h2>
<form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Create</button>
</form>

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'js/showrooms/create-showrooms.js' %}"></script>

<script>
    $(document).ready(function() {
      $('.select2').select2({
        placeholder: "Search and select collaborators",
        width: '45%',
      });
    });
</script>
{% endblock %}

flaire/templates/showrooms/showroom-detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Showroom Title{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/showrooms/showroom-detail.css' %}">
{% endblock %}


{% block content %}
<div class="showroom-header">
    <h3 class = "showroom-title" id = "showroom-title">{{ showroom.title }}</h3>
    <input type="text" id="edit-title" style="display: none;" />
    <p class = "fit-n-followers">
        fits: <span id = "outfit_count">{{ outfit_count }}</span>
        <label style="margin-left: 27px;">
            followers:  <span id = "follower-count">{{ follower_count }}</span>
        </label>
        {% if showroom.tags.all %}
        <p class = "tags">
            <span class = > </span>
            {% for tag in showroom.tags.all %}
            #{{ tag.name }}
            {% endfor %}
        </p>
        {% endif %}
    </p>
    <div id = "user-access">
        <div id = "user-icons">
            {% if showroom.owner.profile_picture %}
            <img src = "{{ showroom.owner.profile_picture.url }}"/>
            {% else %}
            <img src= "{% static 'img/user-icon.png' %}" alt="User Profile" style="height: 35px; width: 35px; border-radius: 50%; object-fit: cover">
            {% endif %}

            {% for profile in accepted_collaborators %}
            {% if profile.collaborator.profile_picture %}
            <img src = "{{ profile.collaborator.profile_picture.url }}"/>
            {% else %}
            <img src= "{% static 'img/user-icon.png' %}" alt="User Profile" style="height: 35px; width: 35px; border-radius: 50%; object-fit: cover">
            {% endif %}
            {% endfor %}
        </div>
        <div id = "user-actions">
          {% if if_invited %}
          <button type="button" id = "accept-button" data-state="accept">
            Accept
          </button>
          <button type="button" id = "decline-button" data-state="decline">
            Decline
          </button>
          {% endif %}

          {% if show_follow_button %}
          {% if if_invited %}
          {% else %}
          <button type="button" id = "follow-button" data-state="follow">
            Follow
          </button>
          {% endif %}
          {% endif %}

          {% if show_edit_button %}
          <button type="button" id = "edit-button" data-state="edit">
            Edit
          </button>
          {% endif %}

          {% if if_following %}
          {% if if_invited %}
          {% else %}
          <button type="button" id = "unfollow-button" data-state="unfollow">
            Unfollow
          </button>
          {% endif %}
          {% endif %}
        </div>
    </div>
</div>

<div id="outfits-grid" data-showroom-id ="{{ showroom.id }}">
</div>

<button id ="add-outfits-btn-dt" class = "add-outfits-btn-dt">+</button>

<div id = "create-sr-add-outfits" class="modal">
    <span class="close">&times;</span>
    <h2 id = "add-outfit-modal-header" style="text-align: center; margin-top: 30px;">Add outfits</h2>
    <hr class="custom-line">
    <div class="add-outfits-sr-content" id="add-outfits-sr-content">
    </div>
</div>

<div id="modal-overlay"></div>

<div id="outfit-modal" class="outfit-modal hidden">
  <div class="modal-content">
    <div class="close-btn">&times;</div>
    <img id="modal-image" />

    <div id="modal-text-content">
      <p id="modal-owner" class="username">@username</p>
      <p id="modal-caption" class="caption"></p>
      <p id="modal-tags" class="tags">#tag1 #tag2 #tag3</p>
      <div id="like-button">
        <img src="{% static 'img/unliked.png' %}" alt="Heart Icon">
      </div>

      <div id="mini-navbar">
        <button class="mini-tab active" data-tab="likes">likes</button>
        <button class="mini-tab" data-tab="comments">comments</button>
        <button class="mini-tab" data-tab="list">list items</button>
      </div>

      <div id="modal-tab-content">
        <div id="modal-comments" class="hidden">
          {% if request.user.is_authenticated %}
          <form id="comment-form">
            <textarea id="comment-input" rows="2" placeholder="Add a comment..."></textarea>
            <button type="submit">Post</button>
          </form>
          {% endif %}
          <div id="modal-comments-list"></div>
        </div>

        <!-- listed items section -->
        <div id="modal-listed-items" class="hidden"></div>
      </div>
    </div>
  </div>
</div>

<div id = "oc-user-div">
  <span class="close-ocdiv">&times;</span>
  <h2>Users</h2>
  <hr>
  <ul id = "oc-modal-user-list">
    <!-- owner -->
    <li class = "user-link">
      {% if showroom.owner.profile_picture %}
      <img src="{{ showroom.owner.profile_picture.url }}" alt="{{ showroom.owner.username }}'s profile picture" class="profile-pic-small">
      {% else %}
      <img src= "{% static 'img/user-icon.png' %}" alt="User Profile" style="height: 35px; width: 35px; border-radius: 50%; object-fit: cover" class="profile-pic-small">
      {% endif %}
      <a class="oc-username" href = "{% url 'user_management:other_user_profile' username=showroom.owner.user.username %}">
        {{ showroom.owner.user.username }}
      </a>
    </li>
    <!-- collaborator/s -->
    {% for profile in accepted_collaborators %}
    <li class = "user-link">
      {% if profile.collaborator.profile_picture %}
      <img src = "{{ profile.collaborator.profile_picture.url }}" class="profile-pic-small">
      {% else %}
      <img src= "{% static 'img/user-icon.png' %}" alt="User Profile" style="height: 35px; width: 35px; border-radius: 50%; object-fit: cover" class="profile-pic-small">
      {% endif %}
      <a class="oc-username" href="{% url 'user_management:other_user_profile' username=profile.collaborator.user.username %}">
        {{ profile.collaborator.user.username }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/showrooms/showroom-outfits.js' %}"></script>
<script src="{% static 'js/showrooms/sr-outfits-modal.js' %}"></script>
{% endblock %}